/*
 * 
 *   Copyright 2018  NHS Digital
 * 
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 * 
 *        http://www.apache.org/licenses/LICENSE-2.0
 * 
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *  
 */
package uk.nhs.digital.safetycase.ui.ekit;

import com.hexidec.ekit.EkitCore;
import com.hexidec.ekit.EkitCoreSpell;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author damian
 */
public class EkitDialog
        extends javax.swing.JDialog 
{

    public static final String TOOLBAR = "NW|NS|OP|SV|PR|SP|CT|CP|PS|SP|UN|RE|SP|BL|IT|UD|SP|FN|SP|UC|SP|LK|SP|SR";
    private EkitCoreSpell ekitCore = null;
    private HtmlEditorPanel callerPanel = null;
    
    /**
     * Creates new form EkitDialog
     */
    public EkitDialog(java.awt.Frame parent, String c, HtmlEditorPanel p) {
        super(parent, false);
        initComponents();
        callerPanel = p;
        ekitCore = new EkitCoreSpell(this, p);
        ekitCore.setFrame(parent);
        this.getContentPane().setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.anchor = GridBagConstraints.NORTH;
        gbc.gridheight = 1;
        gbc.gridwidth = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 0.0;
        gbc.gridx = 1;

        gbc.gridy = 1;
        this.getContentPane().add(ekitCore.getToolBarMain(true), gbc);

        gbc.gridy = 2;
        this.getContentPane().add(ekitCore.getToolBarFormat(true), gbc);

        gbc.gridy = 3;
        this.getContentPane().add(ekitCore.getToolBarStyles(true), gbc);

        gbc.anchor = GridBagConstraints.SOUTH;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.weighty = 1.0;
        gbc.gridy = 4;
        this.getContentPane().add(ekitCore, gbc);
	this.setJMenuBar(ekitCore.getMenuBar());
        
        ekitCore.getTextPane().setText(c);
        ekitCore.getSourcePane().setText(c);
        
        pack();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 723, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
