/*
 * 
 *   Copyright 2018  NHS Digital
 * 
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 * 
 *        http://www.apache.org/licenses/LICENSE-2.0
 * 
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *  
 */
package uk.nhs.digital.projectuiframework;

import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import javax.swing.ImageIcon;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.rendering.PDFRenderer;
import uk.nhs.digital.projectuiframework.smart.SmartProject;

/**
 * Content for the tabbed panel when the application first starts.
 * @author damian
 */
public class InitialTab extends javax.swing.JPanel {

    private PDFRenderer renderer = null;
    /**
     * Creates new form InitialTab
     */
    public InitialTab() {
        initComponents();
        String p = System.getProperty("uk.nhs.digital.projectuiframework.initialtab");
        if (p.startsWith("internal:")) {
            p = p.substring(p.indexOf(":") + 1);
            try {
                InputStream is = getClass().getResourceAsStream(p);
                PDDocument initialPage = PDDocument.load(is);
                renderer = new PDFRenderer(initialPage);
//                initialPageLabel.setVisible(true);
                BufferedImage image = renderer.renderImageWithDPI(0, 100);
                initialPageLabel.setIcon(new ImageIcon(image));
            }
            catch (IOException e) {
                SmartProject.getProject().log("Error loading initial tab", e);
            }
            catch (Exception eother) {
                eother.printStackTrace();
                System.exit(1);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        initialPageScrollPanel = new javax.swing.JScrollPane();
        initialPageLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        initialPageScrollPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        initialPageScrollPanel.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        initialPageScrollPanel.setViewportView(initialPageLabel);

        add(initialPageScrollPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel initialPageLabel;
    private javax.swing.JScrollPane initialPageScrollPanel;
    // End of variables declaration//GEN-END:variables
}
