/*
 * 
 *   Copyright 2017  NHS Digital
 * 
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 * 
 *        http://www.apache.org/licenses/LICENSE-2.0
 * 
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *  
 */
package uk.nhs.digital.safetycase.ui;

import java.util.Iterator;
import javax.swing.DefaultListModel;
import javax.swing.border.TitledBorder;
import uk.nhs.digital.safetycase.data.MetaFactory;

/**
 *
 * @author murff
 */
public class LibraryEditorDialog extends javax.swing.JDialog {

    private LibraryTablePanel libraryTablePanel = new LibraryTablePanel();
    /**
     * Creates new form LibraryEditorDialog
     */
    public LibraryEditorDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try {
            Iterator<String> lnames = MetaFactory.getInstance().getLibrary().getLibraryNames();
            DefaultListModel dlm = new DefaultListModel();
            while (lnames.hasNext()) {
                String s = lnames.next();
                dlm.addElement(s);
            }
            libraryList.setModel(dlm);
            librarySplitPane.setTopComponent(libraryTablePanel);
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        libraryEditorSplitPane = new javax.swing.JSplitPane();
        libraryTypesPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        libraryList = new javax.swing.JList<>();
        closeButton = new javax.swing.JButton();
        libraryPanel = new javax.swing.JPanel();
        librarySplitPane = new javax.swing.JSplitPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        libraryTable = new javax.swing.JTable();
        libraryObjectPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sourceTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        commentTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Libraries");

        libraryList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        libraryList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                libraryListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(libraryList);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout libraryTypesPanelLayout = new javax.swing.GroupLayout(libraryTypesPanel);
        libraryTypesPanel.setLayout(libraryTypesPanelLayout);
        libraryTypesPanelLayout.setHorizontalGroup(
            libraryTypesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(libraryTypesPanelLayout.createSequentialGroup()
                .addComponent(closeButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        libraryTypesPanelLayout.setVerticalGroup(
            libraryTypesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(libraryTypesPanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(closeButton))
        );

        libraryEditorSplitPane.setLeftComponent(libraryTypesPanel);

        libraryPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("(No selection)"));
        libraryPanel.setLayout(new java.awt.CardLayout());

        librarySplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        libraryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        libraryTable.setMaximumSize(new java.awt.Dimension(2147483647, 264));
        libraryTable.setMinimumSize(new java.awt.Dimension(60, 264));
        libraryTable.setPreferredSize(new java.awt.Dimension(300, 264));
        jScrollPane2.setViewportView(libraryTable);

        librarySplitPane.setTopComponent(jScrollPane2);

        jLabel2.setText("Name");

        jLabel3.setText("Source");

        jLabel4.setText("Description");

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setLineWrap(true);
        descriptionTextArea.setRows(5);
        descriptionTextArea.setWrapStyleWord(true);
        jScrollPane3.setViewportView(descriptionTextArea);

        jLabel5.setText("Comment");

        commentTextArea.setColumns(20);
        commentTextArea.setLineWrap(true);
        commentTextArea.setRows(5);
        commentTextArea.setWrapStyleWord(true);
        jScrollPane4.setViewportView(commentTextArea);

        javax.swing.GroupLayout libraryObjectPanelLayout = new javax.swing.GroupLayout(libraryObjectPanel);
        libraryObjectPanel.setLayout(libraryObjectPanelLayout);
        libraryObjectPanelLayout.setHorizontalGroup(
            libraryObjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(libraryObjectPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(libraryObjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(libraryObjectPanelLayout.createSequentialGroup()
                        .addGroup(libraryObjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(libraryObjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameTextField)
                            .addComponent(sourceTextField)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                    .addGroup(libraryObjectPanelLayout.createSequentialGroup()
                        .addGroup(libraryObjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        libraryObjectPanelLayout.setVerticalGroup(
            libraryObjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(libraryObjectPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(libraryObjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(libraryObjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sourceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        librarySplitPane.setRightComponent(libraryObjectPanel);

        libraryPanel.add(librarySplitPane, "card2");

        libraryEditorSplitPane.setRightComponent(libraryPanel);

        getContentPane().add(libraryEditorSplitPane, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void libraryListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libraryListMouseClicked
        String s = libraryList.getSelectedValue();
        libraryPanel.setBorder(new TitledBorder(s));
    }//GEN-LAST:event_libraryListMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JTextArea commentTextArea;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane libraryEditorSplitPane;
    private javax.swing.JList<String> libraryList;
    private javax.swing.JPanel libraryObjectPanel;
    private javax.swing.JPanel libraryPanel;
    private javax.swing.JSplitPane librarySplitPane;
    private javax.swing.JTable libraryTable;
    private javax.swing.JPanel libraryTypesPanel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField sourceTextField;
    // End of variables declaration//GEN-END:variables
}
