/*
 * 
 *   Copyright 2017  NHS Digital
 * 
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 * 
 *        http://www.apache.org/licenses/LICENSE-2.0
 * 
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *  
 */
package uk.nhs.digital.safetycase.ui.processeditor;

import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import uk.nhs.digital.safetycase.data.Hazard;
import uk.nhs.digital.safetycase.data.MetaFactory;
import uk.nhs.digital.safetycase.data.ProcessStep;
import uk.nhs.digital.safetycase.data.Relationship;
import uk.nhs.digital.safetycase.ui.LinkEditor;

/**
 *
 * @author murff
 */
public class ProcessStepDetail extends javax.swing.JPanel {

    private static final String[] COLUMNS = {"Name", "Status", "Initial rating", "Residual rating"};
    private JDialog parent = null;
    private ProcessStep processStep = null;
    /**
     * Creates new form ProcessStepDetail
     */
    public ProcessStepDetail(ProcessStep ps) {
        initComponents();
        processStep = ps;
        if (ps != null) {
            populate();
        } else {
            DefaultTableModel dtm = new DefaultTableModel(COLUMNS, 0);
            hazardsTable.setModel(dtm);
        }
    }

    private void populate() {
        nameTextField.setText(processStep.getAttributeValue("Name"));
        nameTextField.setEditable(false);
        descriptionTextArea.setText(processStep.getAttributeValue("Description"));
        
        try { 
            ArrayList<Relationship> hazards = processStep.getRelationships("Hazard");
            DefaultTableModel dtm = new DefaultTableModel(COLUMNS, 0);
            if (hazards != null) {
                for (Relationship r : hazards) {
                    Hazard h = (Hazard)MetaFactory.getInstance().getFactory("Hazard").get(r.getTarget());
                    String[] row = new String[COLUMNS.length];
                    row[0] = h.getAttributeValue("Name");
                    row[1] = h.getAttributeValue("Status");
                    row[2] = h.getAttributeValue("InitialRiskRating");
                    row[3] = h.getAttributeValue("ResidualRiskRating");
                    dtm.addRow(row);
                }
            }
            hazardsTable.setModel(dtm);
            systemLinksPanel.setDisplay(processStep, "System");
            functionsLinksPanel.setDisplay(processStep, "SystemFunction");
            locationsLinksPanel.setDisplay(processStep, "Location");
            rolesLinksPanel.setDisplay(processStep, "Role");
            
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public ProcessStepDetail setParent(JDialog p) {
        parent = p;
        return this;
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        hazardsPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        hazardsTable = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        systemLinksPanel = new uk.nhs.digital.safetycase.ui.processeditor.OtherLinksPanel();
        functionsLinksPanel = new uk.nhs.digital.safetycase.ui.processeditor.OtherLinksPanel();
        locationsLinksPanel = new uk.nhs.digital.safetycase.ui.processeditor.OtherLinksPanel();
        rolesLinksPanel = new uk.nhs.digital.safetycase.ui.processeditor.OtherLinksPanel();
        closeButton = new javax.swing.JButton();
        editLinksButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Process step"));
        setMaximumSize(new java.awt.Dimension(695, 505));
        setMinimumSize(new java.awt.Dimension(695, 505));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 31, -1, -1));
        add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 29, 569, -1));

        jLabel2.setText("Description");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 66, -1, -1));

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setRows(5);
        descriptionTextArea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                descriptionTextAreaFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(descriptionTextArea);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 87, 661, -1));

        hazardsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Identified hazards"));

        hazardsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(hazardsTable);

        javax.swing.GroupLayout hazardsPanelLayout = new javax.swing.GroupLayout(hazardsPanel);
        hazardsPanel.setLayout(hazardsPanelLayout);
        hazardsPanelLayout.setHorizontalGroup(
            hazardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hazardsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
                .addContainerGap())
        );
        hazardsPanelLayout.setVerticalGroup(
            hazardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hazardsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(hazardsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 171, 661, 180));

        jTabbedPane1.addTab("Systems", systemLinksPanel);
        jTabbedPane1.addTab("Functions", functionsLinksPanel);
        jTabbedPane1.addTab("Care settings", locationsLinksPanel);
        jTabbedPane1.addTab("Roles", rolesLinksPanel);

        add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 661, 180));

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 570, -1, -1));

        editLinksButton.setText("Links...");
        editLinksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editLinksButtonActionPerformed(evt);
            }
        });
        add(editLinksButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 570, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        try {
            MetaFactory.getInstance().getFactory(processStep.getDatabaseObjectName()).put(processStep);
        }
        catch (Exception e) {
            e.printStackTrace();
        }
        parent.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void editLinksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editLinksButtonActionPerformed
        JDialog linkEditor = new JDialog(JOptionPane.getFrameForComponent(this), true);
        linkEditor.add(new LinkEditor(processStep).setParent(linkEditor));
        linkEditor.pack();
        linkEditor.setVisible(true);
        
        populate();
    }//GEN-LAST:event_editLinksButtonActionPerformed

    private void descriptionTextAreaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descriptionTextAreaFocusLost
        processStep.setAttribute("Description", descriptionTextArea.getText());
    }//GEN-LAST:event_descriptionTextAreaFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JButton editLinksButton;
    private uk.nhs.digital.safetycase.ui.processeditor.OtherLinksPanel functionsLinksPanel;
    private javax.swing.JPanel hazardsPanel;
    private javax.swing.JTable hazardsTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private uk.nhs.digital.safetycase.ui.processeditor.OtherLinksPanel locationsLinksPanel;
    private javax.swing.JTextField nameTextField;
    private uk.nhs.digital.safetycase.ui.processeditor.OtherLinksPanel rolesLinksPanel;
    private uk.nhs.digital.safetycase.ui.processeditor.OtherLinksPanel systemLinksPanel;
    // End of variables declaration//GEN-END:variables
}
