/*
 * 
 *   Copyright 2017  NHS Digital
 * 
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 * 
 *        http://www.apache.org/licenses/LICENSE-2.0
 * 
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *  
 */
package uk.nhs.digital.safetycase.ui.processeditor;

import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import uk.nhs.digital.projectuiframework.Project;
import uk.nhs.digital.safetycase.data.MetaFactory;
import uk.nhs.digital.safetycase.data.PersistableFactory;

/**
 *
 * @author damian
 */
public class ProcessListForm extends javax.swing.JPanel {

    private ProcessEditor processEditor = null;
    private final String[] columns = {"ID", "Name", "Description", "Created"};
    
    /**
     * Creates new form ProcessListForm
     */
    public ProcessListForm(ProcessEditor p) {
        initComponents();
        processEditor = p;
        DefaultTableModel d = new DefaultTableModel(columns, 0);
        processTable.setModel(d);
    }

    void setTableModel(DefaultTableModel m) {
        processTable.setModel(m);
    }
    
    DefaultTableModel getTableModel() { return (DefaultTableModel)processTable.getModel(); }
    
    void setSelected(int s) {
        processTable.clearSelection();
        processTable.setRowSelectionInterval(s,s);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        processListToolBar = new javax.swing.JToolBar();
        newButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        processTable = new javax.swing.JTable();

        processListToolBar.setRollover(true);

        newButton.setText("New");
        newButton.setFocusable(false);
        newButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });
        processListToolBar.add(newButton);

        deleteButton.setText("Delete");
        deleteButton.setFocusable(false);
        deleteButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        processListToolBar.add(deleteButton);

        editButton.setText("Edit");
        editButton.setFocusable(false);
        editButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        processListToolBar.add(editButton);

        processTable.setAutoCreateRowSorter(true);
        processTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        processTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        processTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                processTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(processTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(processListToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(processListToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void processTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_processTableMouseClicked

        int r = processTable.getSelectedRow();
        String id = (String)processTable.getModel().getValueAt(r, 0);
        processEditor.setSelectedProcess(Integer.parseInt(id));
    }//GEN-LAST:event_processTableMouseClicked

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        JDialog singleProcessEditor = new JDialog(JOptionPane.getFrameForComponent(this), true);
        singleProcessEditor.add(new SingleProcessEditorPanel().setParent(singleProcessEditor).setEditor(processEditor));
        singleProcessEditor.pack();
        singleProcessEditor.setVisible(true);
    }//GEN-LAST:event_newButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        try {
            int dialogResult = JOptionPane.showConfirmDialog(null, "Delete this Process ?", "Warning", JOptionPane.YES_NO_OPTION);
            if (dialogResult == JOptionPane.NO_OPTION) {
                return;
            }
            
            int r = processTable.getSelectedRow();
            String id = (String)processTable.getModel().getValueAt(r, 0);
            MetaFactory mf = MetaFactory.getInstance();
            PersistableFactory<uk.nhs.digital.safetycase.data.Process> pfp = mf.getFactory("Process");
            uk.nhs.digital.safetycase.data.Process p = pfp.get(Integer.parseInt(id));
            pfp.delete(p);
            DefaultTableModel dtm = (DefaultTableModel)processTable.getModel();
            dtm.removeRow(r);
            processEditor.getEditorComponent().notifyEditorEvent(Project.DELETE, p);
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        try {
            int r = processTable.getSelectedRow();
            String id = (String)processTable.getModel().getValueAt(r, 0);
            MetaFactory mf = MetaFactory.getInstance();
            PersistableFactory<uk.nhs.digital.safetycase.data.Process> pfp = mf.getFactory("Process");
            uk.nhs.digital.safetycase.data.Process p = pfp.get(Integer.parseInt(id));
            JDialog singleProcessEditor = new JDialog(JOptionPane.getFrameForComponent(this), true);
            singleProcessEditor.add(new SingleProcessEditorForm(p.getId()).setParent(singleProcessEditor).setEditor(processEditor));
            singleProcessEditor.pack();
            singleProcessEditor.setVisible(true);
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_editButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newButton;
    private javax.swing.JToolBar processListToolBar;
    private javax.swing.JTable processTable;
    // End of variables declaration//GEN-END:variables
}
