/*
 * 
 *   Copyright 2017  NHS Digital
 * 
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 * 
 *        http://www.apache.org/licenses/LICENSE-2.0
 * 
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *  
 */
package uk.nhs.digital.safetycase.ui.processeditor;

import javax.swing.JDialog;
import javax.swing.table.DefaultTableModel;
import uk.nhs.digital.safetycase.data.ProcessStep;
import uk.nhs.digital.safetycase.ui.LinkEditor;

/**
 *
 * @author murff
 */
public class ProcessStepDetail extends javax.swing.JPanel {

    private static final String[] COLUMNS = {"Name", "Status", "Initial rating", "Residual rating"};
    private JDialog parent = null;
    /**
     * Creates new form ProcessStepDetail
     */
    public ProcessStepDetail(ProcessStep ps) {
        initComponents();
        DefaultTableModel dtm = new DefaultTableModel(COLUMNS, 0);
        hazardsTable.setModel(dtm);
    }
    
    public ProcessStepDetail setParent(JDialog p) {
        parent = p;
        return this;
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        hazardsPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        hazardsTable = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        newHazardButton = new javax.swing.JButton();
        editHazardButton = new javax.swing.JButton();
        deleteHazardButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        systemLinksPanel = new uk.nhs.digital.safetycase.ui.processeditor.OtherLinksPanel();
        functionsLinksPanel = new uk.nhs.digital.safetycase.ui.processeditor.OtherLinksPanel();
        locationsLinksPanel = new uk.nhs.digital.safetycase.ui.processeditor.OtherLinksPanel();
        rolesLinksPanel = new uk.nhs.digital.safetycase.ui.processeditor.OtherLinksPanel();
        closeButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Process step"));
        setMaximumSize(new java.awt.Dimension(695, 505));
        setMinimumSize(new java.awt.Dimension(695, 505));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 31, -1, -1));
        add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 29, 569, -1));

        jLabel2.setText("Description");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 66, -1, -1));

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setRows(5);
        jScrollPane1.setViewportView(descriptionTextArea);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 87, 661, -1));

        hazardsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Identified hazards"));

        hazardsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(hazardsTable);

        jToolBar1.setRollover(true);

        newHazardButton.setText("New");
        newHazardButton.setFocusable(false);
        newHazardButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newHazardButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(newHazardButton);

        editHazardButton.setText("Edit");
        editHazardButton.setFocusable(false);
        editHazardButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editHazardButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(editHazardButton);

        deleteHazardButton.setText("Delete");
        deleteHazardButton.setFocusable(false);
        deleteHazardButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteHazardButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(deleteHazardButton);

        javax.swing.GroupLayout hazardsPanelLayout = new javax.swing.GroupLayout(hazardsPanel);
        hazardsPanel.setLayout(hazardsPanelLayout);
        hazardsPanelLayout.setHorizontalGroup(
            hazardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hazardsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hazardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        hazardsPanelLayout.setVerticalGroup(
            hazardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hazardsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(hazardsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 171, 661, 200));

        jTabbedPane1.addTab("Systems", systemLinksPanel);
        jTabbedPane1.addTab("Functions", functionsLinksPanel);
        jTabbedPane1.addTab("Care settings", locationsLinksPanel);
        jTabbedPane1.addTab("Roles", rolesLinksPanel);

        add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 379, 661, 180));

        closeButton.setText("Close");
        add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 570, -1, -1));

        saveButton.setText("Save");
        add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 570, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JButton deleteHazardButton;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JButton editHazardButton;
    private uk.nhs.digital.safetycase.ui.processeditor.OtherLinksPanel functionsLinksPanel;
    private javax.swing.JPanel hazardsPanel;
    private javax.swing.JTable hazardsTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private uk.nhs.digital.safetycase.ui.processeditor.OtherLinksPanel locationsLinksPanel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton newHazardButton;
    private uk.nhs.digital.safetycase.ui.processeditor.OtherLinksPanel rolesLinksPanel;
    private javax.swing.JButton saveButton;
    private uk.nhs.digital.safetycase.ui.processeditor.OtherLinksPanel systemLinksPanel;
    // End of variables declaration//GEN-END:variables
}
