/*
 * 
 *   Copyright 2017  NHS Digital
 * 
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 * 
 *        http://www.apache.org/licenses/LICENSE-2.0
 * 
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *  
 */
package uk.nhs.digital.safetycase.ui.systemeditor;

import uk.nhs.digital.safetycase.ui.systemeditor.*;
import java.util.ArrayList;
import java.util.Collection;
import javax.swing.JDialog;
import uk.nhs.digital.safetycase.data.MetaFactory;
import uk.nhs.digital.safetycase.data.Persistable;
import uk.nhs.digital.safetycase.data.PersistableFactory;
import uk.nhs.digital.safetycase.data.System;

/**
 *
 * @author damian
 */
public class SingleSystemEditorForm extends javax.swing.JPanel {

    private JDialog parent = null;
    private SystemEditor editor = null;
    
    private System system = null;

    /**
     * Creates new form SingleSystemEditorForm
     */
    public SingleSystemEditorForm(int pid)
            throws Exception
    {
        initComponents();
        
        PersistableFactory<System> pfp = (PersistableFactory<System>)MetaFactory.getInstance().getFactory("System");
        if (pid != -1) {
            system = pfp.get(pid);
            systemEditor.setData(system.getAttributeValue("Name"), system.getAttributeValue("Version"), system.getAttributeValue("Description"));
            systemEditor.setSystemId(pid);
//            ArrayList<Persistable> ps = MetaFactory.getInstance().getChildren("SystemStep", "SystemID", pid);
//            stepList.populateList(ps);
        }
    }

    SingleSystemEditorForm setParent(JDialog p) {
        parent = p;
        systemEditor.setParent(p);
        return this;
    }
    
    
    SingleSystemEditorForm setEditor(SystemEditor p) { 
        editor = p; 
        systemEditor.setEditor(p);
        return this;
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();

        setLayout(new java.awt.CardLayout());

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        add(jSplitPane1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
    private uk.nhs.digital.safetycase.ui.systemeditor.SingleSystemEditorPanel systemEditor;
}
